from __future__ import annotations

from pathlib import Path
import re


def scaffold_device(library_root: str | Path, vendor: str, part_number: str, technology: str = "SiC MOSFET") -> Path:
    vendor_slug = re.sub(r"[^a-z0-9]+", "-", vendor.lower()).strip("-")
    part_slug = re.sub(r"[^A-Za-z0-9._-]+", "-", part_number).strip("-")
    root = Path(library_root) / vendor_slug / part_slug
    if root.exists() and any(root.iterdir()):
        raise FileExistsError(f"device directory is not empty: {root}")
    for directory in ("curves", "calibration", "validation", "manufacturer_models"):
        (root / directory).mkdir(parents=True, exist_ok=True)
    manifest = f'''schema_version: 1
device_id: {part_slug}
vendor: {vendor}
part_number: {part_number}
technology: {technology}
status: scaffold
data_sources: {{}}
curves: {{}}
calibrations:
  M0: null
  M1: null
  M2: null
  M3: null
supported_domain: {{}}
notes:
  - Replace scaffold fields only with traceable extracted or measured data.
'''
    (root / "manifest.yaml").write_text(manifest, encoding="utf-8")
    (root / "README.md").write_text(
        f"# {part_number}\n\nDevice workspace generated by PowerSemiForge.\n\n"
        "Every parameter and curve must retain source file, page/locator, units, conditions, and extraction version.\n",
        encoding="utf-8",
    )
    return root

